#!/usr/bin/env bash
# Prepare one user-operated, behavior-neutral online evidence run.
set -euo pipefail

ROOT="/home/richard/simenv_official_clean"
OUTPUT_ROOT="${CONTROLLED_YAW_SHADOW_OUTPUT_ROOT:-$ROOT/debug/controlled_online_yaw_shadow}"
POLICY_PATH="$ROOT/src/unitree_guide/logs/policy_act_inference_stair.pt"
POLICY_SHA256="2d5aa72511c0c6609c02f4105845eee6974d3d73431497f8f35306da9588fe14"

[[ -f "$POLICY_PATH" ]] || { echo "missing frozen stair policy: $POLICY_PATH" >&2; exit 65; }
[[ "$(sha256sum "$POLICY_PATH" | awk '{print $1}')" == "$POLICY_SHA256" ]] || {
  echo "frozen stair policy hash mismatch" >&2
  exit 65
}

RUN_TAG="controlled_yaw_shadow_$(date +%Y%m%d_%H%M%S)"
RUN_ROOT="$OUTPUT_ROOT/$RUN_TAG"
ENV_FILE="$OUTPUT_ROOT/current.env"
STAGE_B_ROOT="$RUN_ROOT/room_search_stage_b"
STARTUP_ANCHOR_DIR="$RUN_ROOT/startup_anchor"
STARTUP_ANCHOR_READY_FILE="$STARTUP_ANCHOR_DIR/recorder.ready.json"
# The validation archive, P2KG9U bundle, state machine and observer must share
# one identity; component type belongs in the directory, not the run id.
P2KG9_RUN_ID="${RUN_TAG}"
P2KG9_ENV_FILE="$ROOT/debug/odom_accuracy_audit_v1/p2kg9_current_door_portal_shadow_048/online_run/p2kg9u_${P2KG9_RUN_ID}.env.sh"

# A spawn-anchor audit must use values explicitly supplied for this run.  Do
# not silently copy auto.sh defaults: that would not prove the historical
# launch input.  auto.sh consumes these same exported variables unchanged.
for REQUIRED_SPAWN_VALUE in SPAWN_ROBOT_X SPAWN_ROBOT_Y SPAWN_ROBOT_Z SPAWN_ROBOT_YAW; do
  [[ -n "${!REQUIRED_SPAWN_VALUE:-}" ]] || {
    echo "missing explicit $REQUIRED_SPAWN_VALUE for spawn-anchor audit" >&2
    exit 64
  }
done

[[ ! -e "$RUN_ROOT" ]] || { echo "run output already exists: $RUN_ROOT" >&2; exit 66; }
mkdir -p "$STAGE_B_ROOT/snapshots" "$STAGE_B_ROOT/results" "$STAGE_B_ROOT/logs" "$RUN_ROOT/source_control" "$STARTUP_ANCHOR_DIR"
git -C "$ROOT" diff --binary HEAD -- scripts/local_subgoal_runner_mvp/navigation_state_machine.py \
  > "$RUN_ROOT/source_control/c1_c2_navigation_exact.diff"
NAV_HASH="$(sha256sum "$ROOT/scripts/local_subgoal_runner_mvp/navigation_state_machine.py" | awk '{print $1}')"

umask 077
cat > "$RUN_ROOT/manual_run.env" <<EOF
# Generated by prepare_manual_run.sh. Source this file; do not edit it.
export RUN_TAG=$(printf '%q' "$RUN_TAG")
export ROOM_LOCAL_VALIDATION_RUN_ID=$(printf '%q' "$RUN_TAG")
export CONTROLLED_YAW_SHADOW_RUN_ROOT=$(printf '%q' "$RUN_ROOT")
export P2KG9_RUN_ID=$(printf '%q' "$P2KG9_RUN_ID")
export P2KG9_ENV_FILE=$(printf '%q' "$P2KG9_ENV_FILE")
export RUNTIME_SESSION=$(printf '%q' "${RUN_TAG}_runtime")
export ROOM_SEARCH_STAGE_B_SHADOW=true
export ROOM_SEARCH_STAGE_B_MODE=MULTI_DECISION
export ROOM_SEARCH_STAGE_B_SHADOW_DIR=$(printf '%q' "$STAGE_B_ROOT/snapshots")
export ROOM_SEARCH_STAGE_B_SHADOW_RESULT_DIR=$(printf '%q' "$STAGE_B_ROOT/results")
export ROOM_SEARCH_STAGE_B_SHADOW_PID_FILE=$(printf '%q' "$STAGE_B_ROOT/sidecar.pid")
export ROOM_SEARCH_STAGE_B_SHADOW_LOG_FILE=$(printf '%q' "$STAGE_B_ROOT/logs/sidecar.log")
export ROOM_SEARCH_STAGE_B_SHADOW_READY_FILE=$(printf '%q' "$STAGE_B_ROOT/sidecar.ready.json")
export ROOM_SEARCH_STAGE_B_EVALUATOR_TIMEOUT_SEC=30
export ROOM_SEARCH_OBSERVATION_ARRIVAL_SHADOW=true
export ROOM_SEARCH_C1_C2_NAVIGATION_BEFORE_HASH=$(printf '%q' "$NAV_HASH")
export ROOM_SEARCH_C1_C2_EXACT_DIFF_FILE=$(printf '%q' "$RUN_ROOT/source_control/c1_c2_navigation_exact.diff")
export UNITREE_RL_POLICY=stair
export ROBOT_X=$(printf '%q' "$SPAWN_ROBOT_X")
export ROBOT_Y=$(printf '%q' "$SPAWN_ROBOT_Y")
export ROBOT_Z=$(printf '%q' "$SPAWN_ROBOT_Z")
export ROBOT_YAW=$(printf '%q' "$SPAWN_ROBOT_YAW")
export STARTUP_ANCHOR_SPAWN_SOURCE=EXPLICIT_AUDIT_WRAPPER_ENV
export STARTUP_ANCHOR_AUDIT_ENABLED=1
export STARTUP_ANCHOR_RUN_ID=$(printf '%q' "$RUN_TAG")
export STARTUP_ANCHOR_ARCHIVE_DIR=$(printf '%q' "$STARTUP_ANCHOR_DIR")
export STARTUP_ANCHOR_READY_FILE=$(printf '%q' "$STARTUP_ANCHOR_READY_FILE")
unset ROOM_SEARCH_FROZEN_DECISION_CAPTURE
EOF
chmod 600 "$RUN_ROOT/manual_run.env"
cp "$RUN_ROOT/manual_run.env" "$ENV_FILE"
chmod 600 "$ENV_FILE"

cat > "$RUN_ROOT/prepare_result.json" <<EOF
{
  "schema_version": "controlled_online_yaw_shadow_prepare_v1",
  "run_tag": "$RUN_TAG",
  "runtime_session": "${RUN_TAG}_runtime",
  "p2kg9_run_id": "$P2KG9_RUN_ID",
  "room_search_stage_b_mode": "MULTI_DECISION",
  "room_search_observation_arrival_shadow": true,
  "continuous_yaw_shadow_authority": "audit_only_via_p2kg9_bundle",
  "startup_anchor_audit": {"enabled": true, "archive_dir": "$STARTUP_ANCHOR_DIR", "ready_file": "$STARTUP_ANCHOR_READY_FILE", "authority": "audit_only"},
  "policy": {"name": "stair", "path": "src/unitree_guide/logs/policy_act_inference_stair.pt", "sha256": "$POLICY_SHA256"},
  "behavior_change": false
}
EOF

echo "CONTROLLED_ONLINE_ENV_READY"
echo "ENV_FILE=$ENV_FILE"
echo "RUN_TAG=$RUN_TAG"
echo "P2KG9_RUN_ID=$P2KG9_RUN_ID"
